version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./config/backend.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"

